### PR TITLE
Add `rawString` to markdown-parsed tags

### PR DESCRIPTION
**Pull request by tomekwi**
I find #139 a fantastic update. But sometimes you just need the raw string.

For example, we use some tag values as keys when generating a tree representation of our source. For that we need to access the original value of the tags.

It seems wrong to strip HTML tags from markdown-processed strings just to bring back the original. It's also very fragile.

### CODE REVIEW

**Comment by jugglinmike** [comment]
Dox exposes an option called "raw" that, when set to `true`, will forgo Markdown parsing. Not sure if you knew that, but I thought it might be a more direct alternative for you.

**Comment by tomekwi** [comment]
@jugglinmike thanks for the heads up – I've already noticed that in the source.

The thing is, we actually need both of them – the raw string for building the structure of our docs, and the markdown-parsed strings for the docs themselves. What's more – some tags we need in both forms – both the raw string and the markdown-parsed.

I know we can parse `raw` and do the markdown business ourselves. But I guess we're not the only ones out there. After all, before #139 all tag values were left raw, weren't they?

Another idea to consider – maybe leave the `string` raw for backwards-compatibility, and add a `html` property parsed with markdown?

**Comment by jugglinmike** [comment]
> Another idea to consider – maybe leave the string raw for backwards-compatibility, and add a html property parsed with markdown?

That was going to be my next suggestion! That would be a lot more consistent--the `string` attribute would always expose the same thing. For even more consistency, the `description` attribute should probably be treated the same way. And at that point, the `raw` option would be a lot less useful. Some users might want to disable Markdown for performance reasons, but in that case, maybe the option should be called `noMarkdown` or similar.

Talk about scope creep, though! As I'm sure you're aware, I'm not a maintainer. Even assuming you think it's a good idea, it might be best to wait on further review before moving forward with more substantial changes like that.

**Comment by tomekwi** [comment]
Good point with the `description`. BTW, in jsDoc it's just a regular tag – which is implicitly added if the first paragraphs have no tag. http://usejsdoc.org/tags-description.html

**Comment by ChiperSoft** [comment]
@tomekwi I like this idea, but I'm thinking a better API might be to add a `.raw` property onto the tag containing both the original string and description.  eg: `tag.raw.string` and `tag.raw.description`.

Would you be open to revising this PR for that format? I could do it myself (I'm now the maintainer for dox), but I was thinking you might want credit for it.

**Comment by tomekwi** [comment]
@ChiperSoft thanks for picking up the idea, and leaving the way open for me :)

I'm not exactly sure what you mean. As of this PR, parsing this:
```js
/**
 * Markdown *here*
 *
 * @some-tag and *here* again
 */
```

…results in:
```json
[
  {
    "tags": [
      {
        "type": "some-tag",
        "string": "<p>and <em>here</em> again</p>",
        "rawString": "and *here* again"
      }
    ],
    "description": {
      "full": "<p>Markdown <em>here</em></p>",
      "summary": "<p>Markdown <em>here</em></p>",
      "body": ""
    },
    ...
  }
]
```

Do you mean changing that to:
```json
[
  {
    "raw": {
      "tags": [
        {
          "type": "some-tag",
          "string": "and *here* again"
        }
      ],
      "description": {
        "full": "Markdown *here*",
        "summary": "Markdown *here*",
        "body": ""
      }
    },
    "tags": [
      {
        "type": "some-tag",
        "string": "<p>and <em>here</em> again</p>",
      }
    ],
    "description": {
      "full": "<p>Markdown <em>here</em></p>",
      "summary": "<p>Markdown <em>here</em></p>",
      "body": ""
    },
    ...
  }
]
```
?

**Comment by ChiperSoft** [comment]
No no, I mean instead of doing this:

```js
comment.tags.forEach(function (tag) {
  if (tag.description) tag.description = markdown(tag.description);
  if (tag.string && tag.type !== 'alias') {
    tag.rawString = tag.string;
    tag.string = markdown(tag.string);
  }
});
```

Do this:

```js
comment.tags.forEach(function (tag) {
  tag.raw = {};
  if (tag.description) {
    tag.raw.description = tag.description;
    tag.description = markdown(tag.description);
  }
  if (tag.string && tag.type !== 'alias') {
    tag.raw.string = tag.string;
    tag.string = markdown(tag.string);
  }
});
```

**Comment by tomekwi** [comment]
What I'd propose – after the discussion with @jugglinmike and filing #158 – is:
```json
[ { "tags":
    [ { "type": "some-tag"
      , "string": "and *here* again"
      , "html": "<p>and <em>here</em> again</p>"
      }
    , { "type": "description"
      , "string": "Markdown *here*\n\nand more info"
      , "html": "<p>Markdown <em>here</em></p><p>and more info</p>"
      }
    ]
  , "description":
    { "full": "<p>Markdown <em>here</em></p><p>and more info</p>"
    , "summary": "<p>Markdown <em>here</em></p>"
    , "body": "<p>and more info</p>"
    }
  }
]
```

This would ensure backwards compatibility with 0.x – except for adding a new tag, which doesn't seem to be a breaking change.

**Comment by ChiperSoft** [comment]
Err, that would *break* backwards compat, because `string` would no longer contain html as it does today.

If the goal is just to make the raw values available when markdown is enabled, I'd rather do only that.

**Comment by tomekwi** [comment]
Actually, as of the latest release, it seems like `tag.string` is the raw value – contrary to what the readme has been saying :)

See for yourself:
```
$ npm install -g dox
dox@0.6.1
├── commander@0.6.1
├── marked@0.3.3
└── jsdoctypeparser@1.1.4

$ cat <<———— | dox
/**
 * @some-tag with *markdown*
 */
————
[
  {
    "tags": [
      {
        "type": "some-tag",
        "string": "with *markdown*"
      }
    ],
    "description": {
      "full": "",
      "summary": "",
      "body": ""
    },
    "isPrivate": false,
    "isConstructor": false,
    "isEvent": false,
    "ignore": false,
    "line": 1,
    "codeStart": 4
  }
]
```

**Comment by tomekwi** [comment]
This was changed after releasing 0.6.1: #139

**Comment by ChiperSoft** [comment]
Oh, I see, didn't catch that it was a new addition. That does change things.

Yeah, in that case your suggestion makes more sense.

**Comment by tomekwi** [comment]
Mhmm, now I'm just wondering what to do about `tag.description`. This was output as HTML in 0.6.1. Perhaps just export a `tag.string` by `@param` tags as well? That would be the raw string, with type definitions and such:

```
$ cat <<———— | dox
> /**
>  * @param {*} parameter with *markdown*
>  */
> ————
[
  {
    "tags": [
      {
        "type": "param",
        "name": "parameter",
        "description": "<p>with <em>markdown</em></p>",
        "types": [],
        "typesDescription": "<code>*</code>",
        "optional": false,
        "nullable": false,
        "nonNullable": false,
        "variable": false,
        "string": "{*} parameter with *markdown*"
      }
    ],
    ...
]
```

At the moment `tag.string` is not exported by `@param`s.

**Comment by ChiperSoft** [comment]
That sounds like a reasonable approach, yeah.

**Comment by tomekwi** [comment]
Great, I'll try to hack it out tomorrow. Glad that the project is back on track :)

**Comment by ChiperSoft** [comment]
@tomekwi Have you had time to take a stab at that yet? I'm waiting for this PR before I publish 0.7, since it'll change the behavior of tag.string as it lives on master.

**Comment by tomekwi** [comment]
I'm very sorry it takes so long @ChiperSoft – I was a lot more busy than I had expected. Two-three hours and I'm done.

**Comment by tomekwi** [comment]
@ChiperSoft I'm done :) Again, sorry it took so long.

**Comment by ChiperSoft** [comment]
No worries, life changes things.  Could you please merge in tj/master and resolve the conflicts? Also, the readme in your branch still has a reference to rawString

**Comment by tomekwi** [comment]
Thanks for the catch :) I'll rebase on tj/master to keep your history clutter-free. Hold on :)

**Comment by tomekwi** [comment]
Conflicts are out, readme is updated. we're good to go.

We've lost commit comments through the rebase. But the only conflict was the test – we seem to have both fixed it in parallel :)

**Comment by ChiperSoft** [comment]
Perfect, merged. Thanks!

**Pull request merged**
