### PR TITLE
Make regexes more agnostic to code style, and support ES6 classes and exports.

### PR DESCRIPTION
**Pull request by trusktr**
WIP, but PRed for discussion.

### CODE REVIEW

**Comment by trusktr** [comment]
Now the regexes are there, but things like `class method undefined` need to be handled.

**Comment by ChiperSoft** [comment]
Can you get this working with the unit tests?

**Comment by trusktr** [comment]
@ChiperSoft Yep. Just did. :)

**Comment by trusktr** [comment]
Wow, `class method undefined` was my own console.log. Doh. xD

**Comment by trusktr** [comment]
Definitely don't merge this yet. Coming back tomorrow to get the parentContext working properly for the class methods.

**Comment by trusktr** [comment]
I'm still figuring some things out. Putting `@memberOf FooBar` is setting the tag `{type: 'memberOf', parent: 'FooBar'}` but that isn't resulting in a `parentContext` existing for each class member. Hmm...

**Comment by trusktr** [comment]
Ok, I see the problem. When making a class using prototypes, the previous ctx of the current context was type `prototype`, so it keeps the `parentContext` alive for each context, but class ES6 class definitions are a little different.

**Comment by trusktr** [comment]
Near line 100 of lib/dox.js I see

```js

          // starting a new namespace
          if (comment.ctx && (comment.ctx.type === 'prototype' || comment.ctx.type === 'class' || comment.ctx.class === '')){
              console.log('found a parent context.');
            parentContext = comment.ctx;
          }
          // reasons to clear the namespace
          // new property/method in a different constructor
          else if (!parentContext || !comment.ctx || !comment.ctx.constructor || !parentContext.constructor || parentContext.constructor !== comment.ctx.constructor){
            parentContext = null;
          }
```

I think this is where my problem lies:

```js
          else if (!parentContext || !comment.ctx || !comment.ctx.constructor || !parentContext.constructor || parentContext.constructor !== comment.ctx.constructor){
```

Specifically, the value of `parentContext.constructor` is coming out to be `function Object() { [native code] }` instead of a String (the name of the context constructor). Indeed, `parentContext` is an Object literal, so it's constructor is the Object function. It's using that instead of the `constructor` property, causing this conditional not to work as expected.

The contexts being compared look like this:

```js
{ type: 'class',
  contructor: 'FooBar',
  cons: 'FooBar',
  name: 'FooBar',
  extends: 'Foo',
  string: 'new FooBar()' }

{ type: 'constructor',
  constructor: 'FooBar',
  cons: 'FooBar',
  name: 'constructor',
  string: 'FooBar.prototype.constructor()' }
```

They both have the same `constructor` property. hmmm...

**Comment by trusktr** [comment]
Ah, the rare typo. :)

**Comment by trusktr** [comment]
Done, with unit tests.

**Comment by ChiperSoft** [comment]
@evindor any thoughts?

**Comment by trusktr** [comment]
Let me know if there are any patterns I'm not following that I should follow.

**Comment by evindor** [comment]
Whoa, cool, thanks @trusktr. Will review tomorrow.

**Comment by trusktr** [comment]
I'm trying this out on more complex bigger source files, and I'm finding a situation where all contexts are defined. I'm not sure what's causing it yet, but I've gotta find the cause before we can think of merging this in case it's a problem in my changes.

The file I'm trying to parse is https://github.com/infamous/infamous/blob/master/src/PushMenuLayout.js, using the command `dox -S --debug < src/PushMenuLayout.js`, and the output that dox is showing is http://hastebin.com/zenoqicemo.rb.

I'll report back when if I can find the cause.

**Comment by trusktr** [comment]
I'll close this until then.

**Comment by trusktr** [comment]
Oops!, nevermind, I was accidentally on master branch and didn't realize it. xD It's working nicely with the previously mentioned file. I'm making http://npmjs.org/readem using dox. :D

**Comment by creatorrr** [comment]
Any updates on this PR @evindor? Would be great to have ES6 support.

**Comment by ChiperSoft** [comment]
@tj has granted my collaborator access, so I'm now able to merge this. Gonna do some house keeping today and hopefully get a new release out the door.

**Comment by trusktr** [comment]
@ChiperSoft @evindor Thanks for merging.

There's a use case that I haven't accounted for that came up within the last couple weeks on a project: the need for prototype properties, which ES6 currently doesn't support inside the class syntax.

What ends up happening is something like

```js
import _ from 'underscore'

class Foo {
  someMethod() { /* ... */ }
}

_(Foo.prototype).extend({
  someProperty: 'blah'
})
```

We might be able to make the `parseCodeContext` function pluggable so that users can supply extra context rules for things like underscore.extend, jQuery.extend, etc, then this would allow for the parentContext to remain while parsing these prototype properties. Any thoughts?

**Comment by trusktr** [comment]
@ChiperSoft Oh, your comment at https://github.com/tj/dox/issues/156#issuecomment-83100606 would indeed help with this.

**Comment by ChiperSoft** [comment]
One possibility we could consider is converting the big regex if tree into an array of functions.  Loop through them in order until we get a context return value.  Expose the array and then people could add their own parsers.

**Pull request merged**
